# Generated by Django 4.2.11 on 2024-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbored', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='images/'),
        ),
    ]
