# Generated by Django 4.2.11 on 2024-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbored', '0002_audio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(default='teamproject/media/images/defaultpic.jpeg', upload_to='images/'),
        ),
    ]
