# Generated by Django 4.2.11 on 2024-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbored', '0005_alter_audio_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
