# Generated by Django 4.2.11 on 2024-04-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbored', '0006_audio_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
