# Generated by Django 4.2.11 on 2024-04-18 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soundbored', '0007_soundboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='audio',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_audios', to=settings.AUTH_USER_MODEL),
        ),
    ]
