# Generated by Django 4.2.11 on 2024-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbored', '0008_remove_audio_is_favorite_audio_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(default='images/floppy.jpeg', upload_to='images/'),
        ),
    ]
