# Generated by Django 4.2.11 on 2024-04-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbored', '0011_alter_audio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
