# Generated by Django 4.2.11 on 2024-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbored', '0012_alter_audio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(default='images/defaultpic.jpeg', upload_to='images/'),
        ),
    ]
