# Generated by Django 4.2.11 on 2024-04-30 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soundbored', '0014_alter_audio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL),
        ),
    ]
